public enum AudioName
    {
        BackgroundMusic,
        ButtonClick,
        CatJump,
        Rats,
        CatBadJump,
        CatLand,
        MouseCatch,
        StartMusic,
        EndMusic,
        CutrainMusic,
        Wool,
        TutorialMusic,
        CurtainOpenToGame,
        CurtainGameToEnd,
        CurtainEndToOpening,
        CatJumpPrepare,
        RoyalInsideShape,
        TypingLetter
    }
